import { Mona_Sans, DM_Serif_Text } from "next/font/google";
import "./globals.css";

const monaSans = Mona_Sans({
  subsets: ["latin"],
  variable: "--font-mona-sans",
});

const dmSerifText = DM_Serif_Text({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-dm-serif-text",
});

export const metadata = {
  title: "Mojito",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${monaSans.variable} ${dmSerifText.variable} dark antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
